# Generated by Django 6.0.8 on 2026-08-04 22:06

import apps.bookings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(validators=[apps.bookings.models.validar_ventana_salida])),
                ('numero_personas', models.PositiveSmallIntegerField()),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('correo_cliente', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('pagada', 'Pagada, sin asignar'), ('asignada', 'Asignada'), ('cancelada', 'Cancelada (mal clima)'), ('completada', 'Completada')], default='pendiente_pago', max_length=20)),
                ('canal_origen', models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('capitan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='fleet.capitan')),
                ('embarcacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='fleet.embarcacion')),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
