# Generated by Django 6.0.8 on 2026-08-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('cupo_maximo', models.PositiveSmallIntegerField(help_text='Cupo maximo de viajes para este dia. Usalo para cerrar o reducir el dia cuando se sepa que van a faltar embarcaciones.')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
