# Generated by Django 6.0.8 on 2026-08-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_reserva_cancelada_en_reserva_cancelada_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('completo', '100% en linea'), ('anticipo', '30% anticipo en linea, resto en efectivo')], max_length=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='moneda',
            field=models.CharField(choices=[('MXN', 'Pesos mexicanos'), ('USD', 'Dolares')], default='MXN', max_length=3),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
