# Generated by Django 6.0.8 on 2026-08-10 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_reserva_forma_pago_reserva_moneda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='deslinde_aceptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='deslinde_aceptado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='deslinde_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='deslinde_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('pagada', 'Pagada, sin asignar'), ('asignada', 'Asignada'), ('cancelada', 'Cancelada (reembolsada)'), ('completada', 'Completada')], default='pendiente_pago', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_personas',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
