# Generated by Django 6.0.8 on 2026-08-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_reserva_deslinde_aceptado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutAbandonado',
            fields=[
            ],
            options={
                'verbose_name': 'checkout abandonado',
                'verbose_name_plural': 'checkouts abandonados',
                'ordering': ['-creado_en'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bookings.reserva',),
        ),
    ]
