# Generated by Django 6.0.8 on 2026-08-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_checkoutabandonado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='checkout_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
