# Generated by Django 6.0.8 on 2026-08-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_reserva_checkout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='lleva_lunch',
            field=models.BooleanField(default=False, verbose_name='lunch'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pide_bebidas',
            field=models.BooleanField(default=False, verbose_name='bebidas (a cotizar)'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pide_transporte',
            field=models.BooleanField(default=False, verbose_name='transporte (a cotizar)'),
        ),
    ]
