# Generated by Django 6.0.8 on 2026-08-11 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_reserva_lleva_lunch_reserva_pide_bebidas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='efectivo_cobrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='efectivo_cobrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros_en_efectivo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='en_disputa',
            field=models.BooleanField(default=False, verbose_name='en disputa'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto_efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lo que se recibio en efectivo el dia del viaje, incluido lo que el agente haya cotizado aparte.', max_digits=10, null=True, verbose_name='cobrado en efectivo'),
        ),
    ]
