# Generated by Django 6.0.8 on 2026-08-12 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_reserva_efectivo_cobrado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='monto_reembolsado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lo que efectivamente se devolvio por Stripe.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pagada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='reembolsada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='vendedora_asignada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Vendedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='Lo que va en el link que le manda a sus clientes: ?ref=<codigo>. Solo letras, numeros y guiones.', max_length=30, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Desmarcalo para dar de baja a la vendedora sin perder el historial de sus ventas. Un link con el codigo de alguien inactivo ya no atribuye.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vendedora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vendedora',
                'verbose_name_plural': 'vendedoras',
                'ordering': ['usuario__username'],
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='vendedora',
            field=models.ForeignKey(blank=True, help_text='Quien vendio este viaje. Se llena solo si el cliente llego por su link (?ref=), o a mano desde aqui.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='bookings.vendedora'),
        ),
    ]
