# Generated by Django 6.0.8 on 2026-08-14 20:41

import apps.bookings.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_backfill_fechas_de_dinero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='nombre_cliente',
            field=models.CharField(max_length=150, validators=[apps.bookings.validators.validar_nombre_persona]),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefono_cliente',
            field=models.CharField(max_length=20, validators=[apps.bookings.validators.validar_telefono]),
        ),
    ]
