# Generated by Django 6.0.8 on 2026-08-19 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_reserva_nombre_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_personas',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
