# Generated by Django 6.0.8 on 2026-08-20 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_tope_de_personas_en_cinco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
            ],
            options={
                'verbose_name': 'agenda',
                'verbose_name_plural': 'agenda',
                'ordering': ['fecha', 'hora'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bookings.reserva',),
        ),
    ]
