# Generated by Django 6.0.8 on 2026-08-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupodiario',
            name='cupo_maximo',
            field=models.PositiveSmallIntegerField(help_text='Tope de viajes que decide el negocio para este dia. Ponlo en 0 para cerrar el dia (mal clima, festivo), o usalo cuando falten capitanes: el cupo todavia no sabe contarlos. Si lo que falta es una PANGA no uses esto — marcala en "Embarcaciones no disponibles", que registra cual y por que.'),
        ),
    ]
