# Generated by Django 6.0.8 on 2026-08-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_texto_de_cupo_diario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='aviso_asignacion_enviado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
