# Generated by Django 6.0.8 on 2026-08-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_reserva_aviso_asignacion_enviado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='deslinde_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
