# Generated by Django 6.0.8 on 2026-08-28 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_reserva_deslinde_version'),
        ('fleet', '0009_remove_tarifa_precio_lunch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='lleva_lunch',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='pide_transporte',
        ),
        migrations.AddField(
            model_name='reserva',
            name='pide_extras_whatsapp',
            field=models.BooleanField(default=False, verbose_name='extras (a cotizar, reserva manual)'),
        ),
        migrations.CreateModel(
            name='ReservaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_personalizada', models.CharField(blank=True, max_length=255)),
                ('zona', models.CharField(choices=[('centro', 'Centro'), ('periferia', 'Periferia')], max_length=10)),
                ('numero_personas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('precio_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('punto_encuentro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.puntoencuentro')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporte', to='bookings.reserva')),
            ],
            options={
                'verbose_name': 'transporte de la reserva',
                'verbose_name_plural': 'transportes de reserva',
            },
        ),
        migrations.CreateModel(
            name='ReservaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('extras_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.extrasitem')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras_seleccionados', to='bookings.reserva')),
            ],
            options={
                'verbose_name': 'extra seleccionado',
                'verbose_name_plural': 'extras seleccionados',
                'unique_together': {('reserva', 'extras_item')},
            },
        ),
    ]
