# Generated by Django 6.0.8 on 2026-08-29 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_remove_reserva_lleva_lunch_and_more'),
        ('fleet', '0010_codigopromocional'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo_promocional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='fleet.codigopromocional'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='descuento_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
