# Generated by Django 6.0.8 on 2026-08-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_reserva_codigo_promocional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaextra',
            name='cantidad_solicitada',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservatransporte',
            name='personas_solicitadas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
