# Generated by Django 6.0.8 on 2026-09-03 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_reservaextra_cantidad_solicitada_and_more'),
        ('tenancy', '0002_crear_sede_empresa_la_paz'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupodiario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cupos_diarios', to='tenancy.empresa'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='tenancy.empresa'),
        ),
        migrations.AddField(
            model_name='vendedora',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendedoras', to='tenancy.empresa'),
        ),
    ]
