# Generated by Django 6.0.8 on 2026-09-03 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_empresa_no_null'),
        ('tenancy', '0002_crear_sede_empresa_la_paz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupodiario',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vendedora',
            name='codigo',
            field=models.SlugField(help_text='Lo que va en el link que le manda a sus clientes: ?ref=<codigo>. Solo letras, numeros y guiones.', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='cupodiario',
            constraint=models.UniqueConstraint(fields=('empresa', 'fecha'), name='cupodiario_unico_por_empresa_fecha'),
        ),
        migrations.AddConstraint(
            model_name='vendedora',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='vendedora_unico_por_empresa_codigo'),
        ),
    ]
