# Generated by Django 6.0.8 on 2026-09-05 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_unicidad_por_empresa'),
        ('fleet', '0018_crear_servicio_la_paz'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='servicio',
            field=models.ForeignKey(blank=True, help_text='Servicio o experiencia que ampara esta reserva. Vacio = pesca deportiva (legacy).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='fleet.servicio'),
        ),
    ]
