# Generated by Django 6.0.8 on 2026-09-05 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_reserva_servicio'),
        ('fleet', '0018_crear_servicio_la_paz'),
        ('tenancy', '0003_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_salida',
            field=models.DateField(blank=True, help_text='Fecha de check-out / fin de servicio. Vacio en servicios de un solo dia.', null=True),
        ),
        migrations.CreateModel(
            name='ReservaOcupacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocupaciones', to='tenancy.empresa')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocupaciones', to='fleet.recurso')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupaciones', to='bookings.reserva')),
            ],
            options={
                'verbose_name': 'ocupación de recurso',
                'verbose_name_plural': 'ocupaciones de recursos',
                'ordering': ['fecha_inicio', 'recurso'],
            },
        ),
    ]
