# Generated by Django 6.0.8 on 2026-09-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_rls_reservaocupacion'),
        ('fleet', '0019_paquetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='paquete',
            field=models.ForeignKey(blank=True, help_text='Paquete que ampara esta reserva.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='fleet.paquete'),
        ),
    ]
