# Generated by Django 6.0.8 on 2026-09-07 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_reservaocupacion_exclude'),
        ('fleet', '0022_paquete_porcentaje_anticipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaPaquetePersonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquete_personalizaciones', to='bookings.reserva')),
                ('servicio_personalizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.serviciopersonalizacion')),
            ],
            options={
                'verbose_name': 'personalización de paquete',
                'verbose_name_plural': 'personalizaciones de paquete',
                'constraints': [models.UniqueConstraint(fields=('reserva', 'servicio_personalizacion'), name='reservapaquetepers_unico')],
            },
        ),
        migrations.CreateModel(
            name='ReservaPaqueteServicioRemovido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_removidos', to='bookings.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.servicio')),
            ],
            options={
                'verbose_name': 'servicio removido de paquete',
                'verbose_name_plural': 'servicios removidos de paquete',
                'constraints': [models.UniqueConstraint(fields=('reserva', 'servicio'), name='reservapaqueteserviciorem_unico')],
            },
        ),
    ]
