# Generated by Django 6.0.8 on 2026-09-07 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0032_rls_checkout_paquete'),
        ('fleet', '0022_paquete_porcentaje_anticipo'),
        ('tenancy', '0003_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaPaqueteComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_cupo', models.CharField(choices=[('ok', 'Cupo reservado'), ('liberado', 'Liberado (reserva cancelada)')], default='ok', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.empresa')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='bookings.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.servicio')),
            ],
            options={
                'verbose_name': 'componente de paquete',
                'verbose_name_plural': 'componentes de paquete',
                'constraints': [models.UniqueConstraint(fields=('reserva', 'servicio'), name='reservapaquetecomponente_unico')],
            },
        ),
    ]
