# Generated by Django 6.0.8 on 2026-09-07 23:30

from django.db import migrations


def drop_rls_policy(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            DROP POLICY IF EXISTS tenancy_alcance ON bookings_reservapaqueteservicioremovido;
            ALTER TABLE bookings_reservapaqueteservicioremovido NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE bookings_reservapaqueteservicioremovido DISABLE ROW LEVEL SECURITY;
        """)


def reapply_rls_policy(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE bookings_reservapaqueteservicioremovido ENABLE ROW LEVEL SECURITY;
            ALTER TABLE bookings_reservapaqueteservicioremovido FORCE ROW LEVEL SECURITY;
            CREATE POLICY tenancy_alcance ON bookings_reservapaqueteservicioremovido
            FOR ALL
            USING (
              EXISTS (
                SELECT 1 FROM bookings_reserva r
                WHERE r.id = bookings_reservapaqueteservicioremovido.reserva_id
                  AND (r.empresa_id = NULLIF(current_setting('app.current_empresa_id', true), '')::int
                       OR current_setting('app.operador_plataforma', true) = 'on')
              )
            );
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0034_rls_reservapaquetecomponente'),
    ]

    operations = [
        migrations.RunPython(drop_rls_policy, reapply_rls_policy),
        migrations.RemoveConstraint(
            model_name='reservapaqueteservicioremovido',
            name='reservapaqueteserviciorem_unico',
        ),
        migrations.DeleteModel(
            name='ReservaPaqueteServicioRemovido',
        ),
    ]
