# Generated by Django 6.0.8 on 2026-09-08 01:38

from django.db import migrations


def drop_rls_policy(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            DROP POLICY IF EXISTS tenancy_alcance ON bookings_reservatransporte;
            ALTER TABLE bookings_reservatransporte NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE bookings_reservatransporte DISABLE ROW LEVEL SECURITY;
        """)


def reapply_rls_policy(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE bookings_reservatransporte ENABLE ROW LEVEL SECURITY;
            ALTER TABLE bookings_reservatransporte FORCE ROW LEVEL SECURITY;
            CREATE POLICY tenancy_alcance ON bookings_reservatransporte
            FOR ALL
            USING (
              EXISTS (
                SELECT 1 FROM bookings_reserva r
                WHERE r.id = bookings_reservatransporte.reserva_id
                  AND (r.empresa_id = NULLIF(current_setting('app.current_empresa_id', true), '')::int
                       OR current_setting('app.operador_plataforma', true) = 'on')
              )
            );
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0035_remove_reservapaqueteservicioremovido_reservapaqueteserviciorem_unico_and_more'),
    ]

    operations = [
        migrations.RunPython(drop_rls_policy, reapply_rls_policy),
        migrations.DeleteModel(
            name='ReservaTransporte',
        ),
    ]

