# Generated by Django 6.0.8 on 2026-09-09 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0037_alter_reserva_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_personas',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
