# Generated by Django 6.0.8 on 2026-09-09 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0038_alter_reserva_numero_personas'),
        ('fleet', '0029_servicio_hora_apertura_servicio_hora_cierre'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_traslado', models.CharField(choices=[('redondo_aeropuerto', 'Redondo con aeropuerto'), ('redondo_actividad', 'Redondo actividad'), ('recepcion_aeropuerto', 'Recepción aeropuerto')], max_length=25)),
                ('direccion_personalizada', models.CharField(blank=True, default='', max_length=255)),
                ('zona', models.CharField(blank=True, choices=[('centro', 'Centro'), ('periferia', 'Periferia')], default='', max_length=10)),
                ('fecha_regreso', models.DateField(blank=True, help_text='Solo redondo_aeropuerto: día de salida al aeropuerto.', null=True)),
                ('numero_personas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('precio_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('punto_encuentro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.puntoencuentro')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_transporte', to='bookings.reserva')),
            ],
            options={
                'verbose_name': 'detalle de transporte',
                'verbose_name_plural': 'detalles de transporte',
            },
        ),
    ]
