# Generated by Django 6.0.8 on 2026-09-10 00:29

import apps.bookings.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0040_rls_detalletransporte'),
        ('fleet', '0029_servicio_hora_apertura_servicio_hora_cierre'),
        ('tenancy', '0003_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('nombre_cliente', models.CharField(max_length=150, validators=[apps.bookings.validators.validar_nombre_persona])),
                ('telefono_cliente', models.CharField(max_length=20, validators=[apps.bookings.validators.validar_telefono])),
                ('correo_cliente', models.EmailField(max_length=254)),
                ('moneda', models.CharField(choices=[('MXN', 'Pesos mexicanos'), ('USD', 'Dolares')], default='MXN', max_length=3)),
                ('forma_pago', models.CharField(choices=[('completo', '100% en linea'), ('anticipo', '30% anticipo en linea, resto en efectivo')], default='completo', max_length=10)),
                ('estado', models.CharField(choices=[('armando', 'Armando (reservas creadas)'), ('autorizando', 'Autorizando (esperando confirmaciones del cliente)'), ('autorizada', 'Autorizada (lista para capturar)'), ('capturada', 'Capturada (pagada)'), ('cancelada', 'Cancelada')], default='armando', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('notificada_en', models.DateTimeField(blank=True, null=True)),
                ('empresa_lider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_lideradas', to='tenancy.empresa')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='fleet.paquete')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='tenancy.sede')),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'órdenes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='orden',
            field=models.ForeignKey(blank=True, help_text='Orden cruza-empresa que agrupa esta reserva.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='bookings.orden'),
        ),
    ]
