# Generated by Django 6.0.8 on 2026-09-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0046_retirar_reservaextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='inicio_paquete',
            field=models.DateField(blank=True, help_text='Paquete de una sola empresa: primer día del paquete que eligió el cliente. `fecha` es el día de la actividad principal.', null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='personas_por_servicio',
            field=models.JSONField(blank=True, default=dict, help_text='Paquete de una sola empresa: personas de cada servicio, {"<servicio_id>": n}. `numero_personas` es el del componente operativo principal.'),
        ),
    ]
