# Generated by Django 6.0.8 on 2026-10-01 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0048_orden_retomar_notificado_en'),
        ('fleet', '0039_paqueteservicio_salidas'),
        ('tenancy', '0004_la_ventana_puerto_chale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='tenancy.empresa')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='bookings.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet.servicio')),
            ],
            options={
                'verbose_name': 'salida al mar',
                'verbose_name_plural': 'salidas al mar',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['empresa', 'fecha'], name='reservasalida_empresa_fecha')],
                'constraints': [models.UniqueConstraint(fields=('reserva', 'servicio', 'fecha'), name='reservasalida_unica_por_dia')],
            },
        ),
    ]
