# Generated by Django 6.0.8 on 2026-10-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0050_rls_reservasalida'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='aeropuerto',
            field=models.CharField(blank=True, choices=[('lap', 'La Paz (LAP)'), ('sjd', 'Los Cabos (SJD)')], default='', help_text='Paquete con hospedaje y traslado: aeropuerto del que llega la clienta (el traslado es redondo).', max_length=3),
        ),
    ]
