# Generated by Django 6.0.8 on 2026-10-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0051_reserva_aeropuerto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(blank=True, help_text='Hora de salida. Vacía en un paquete que no la pide: la acuerda el capitán durante la estadía.', null=True),
        ),
    ]
