# Generated by Django 6.0.8 on 2026-10-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0052_pide_hora_y_hora_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='tipo_cambio',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, help_text='Pesos por dolar de la sede, congelado al pasar la orden a USD. Vacio en MXN.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_cambio',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, help_text='Pesos por dolar de la sede, congelado al pasar la reserva a USD. Vacio en MXN.', max_digits=8, null=True),
        ),
    ]
