# Generated by Django 6.0.8 on 2026-09-02 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('zona_horaria', models.CharField(default='America/Mazatlan', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'sede',
                'verbose_name_plural': 'sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='Inmutable despues de creada: la URL del webhook de Stripe configurada en su Dashboard depende de este valor.', max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('exclusiva', models.BooleanField(default=False, help_text='Si esta Empresa opera en exclusiva su Sede. Informativo en v1.')),
                ('stripe_secret_key', models.CharField(blank=True, max_length=200)),
                ('stripe_webhook_secret', models.CharField(blank=True, max_length=200)),
                ('stripe_publishable_key', models.CharField(blank=True, max_length=200)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='tenancy.sede')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MembresiaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('JEFE', 'Jefe'), ('VENDEDORA', 'Vendedora')], max_length=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='tenancy.empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membresia de empresa',
                'verbose_name_plural': 'membresias de empresa',
                'unique_together': {('user', 'empresa')},
            },
        ),
    ]
