# Generated by Django 6.0.8 on 2026-10-02 18:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_la_ventana_puerto_chale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='tipo_cambio_usd',
            field=models.DecimalField(db_default=Decimal('18.0000'), decimal_places=4, default=Decimal('18.0000'), help_text='Pesos por 1 dólar. Todos los precios se guardan en pesos; el precio en dólares se calcula con este valor y se redondea hacia arriba al dólar entero.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
    ]
