# Generated by Django 6.0.8 on 2026-10-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_sede_tipo_cambio_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='correos_aviso',
            field=models.CharField(blank=True, help_text='A quien se le avisa por correo cada vez que entra una reserva pagada de esta Empresa. Varias direcciones separadas por coma. Vacio = no se avisa.', max_length=300),
        ),
    ]
