# Generated by Django 6.0.8 on 2026-08-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Embarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('clase', models.CharField(choices=[('chica', 'Chica (máx. 3 personas)'), ('grande', 'Grande (máx. 6 personas)')], max_length=10)),
                ('capacidad_maxima', models.PositiveSmallIntegerField(help_text='Numero maximo de personas que puede llevar esta embarcacion.')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
