# Generated by Django 6.0.8 on 2026-08-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_tarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='precio_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio del tour en dolares. Vacio = no se ofrece pago en USD.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Precio del tour en pesos (MXN).', max_digits=10),
        ),
    ]
