# Generated by Django 6.0.8 on 2026-08-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_tarifa_precio_usd_alter_tarifa_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='precio_persona_extra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cargo en pesos por cada persona arriba de las incluidas en el precio del viaje. 0 = el precio no cambia con el numero de personas.', max_digits=10),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='precio_persona_extra_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='El mismo cargo en dolares. Vacio = no se puede cobrar en USD un viaje que lleve personas extra.', max_digits=10, null=True),
        ),
    ]
