# Generated by Django 6.0.8 on 2026-08-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_tarifa_precio_persona_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='precio_lunch',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio del lunch en pesos, POR PERSONA. El menu es fijo y cambia cada semana, asi que este monto se actualiza aqui.', max_digits=10),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='precio_lunch_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='El mismo precio del lunch en dolares, por persona.', max_digits=10, null=True),
        ),
    ]
