# Generated by Django 6.0.8 on 2026-08-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_tarifa_precio_lunch_tarifa_precio_lunch_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarcacion',
            name='activa',
            field=models.BooleanField(default=True, help_text='Desmarcalo para sacar la panga de la flota sin borrarla (vendida, fuera de servicio). Una panga inactiva deja de contar para el cupo pero conserva los viajes historicos que tiene asignados. Mismo patron que Vendedora.activo: borrarla dejaria viajes sin panga.'),
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='clase',
            field=models.CharField(choices=[('chica', 'Chica'), ('grande', 'Grande')], max_length=10),
        ),
    ]
