# Generated by Django 6.0.8 on 2026-08-19 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_embarcacion_activa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbarcacionNoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, help_text='Mantenimiento, motor descompuesto, prestada. Opcional.', max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='no_disponibles', to='fleet.embarcacion')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embarcaciones_dadas_de_baja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'embarcacion no disponible',
                'verbose_name_plural': 'embarcaciones no disponibles',
                'ordering': ['-fecha', 'embarcacion__nombre'],
                'unique_together': {('fecha', 'embarcacion')},
            },
        ),
    ]
