# Generated by Django 6.0.8 on 2026-08-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_embarcacionnodisponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtrasItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('brunch', 'Brunch'), ('licencia', 'Licencia de pesca'), ('carnada', 'Carnada'), ('otro', 'Otro')], max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en pesos (MXN).', max_digits=10)),
                ('precio_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Precio en dolares. Vacio = no se ofrece en USD.', max_digits=10, null=True)),
                ('cobrar_por_persona', models.BooleanField(default=True, help_text='Marcado: el precio se multiplica por el numero de personas de la reserva (igual que el brunch). Sin marcar: precio plano, se cobra una sola vez por reserva.')),
                ('preseleccionado', models.BooleanField(default=False, help_text='Viene marcado por defecto en el checkout (licencia y carnada).')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'extra del checkout',
                'verbose_name_plural': 'extras del checkout',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PuntoEncuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('zona', models.CharField(choices=[('centro', 'Centro'), ('periferia', 'Periferia')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'punto de encuentro',
                'verbose_name_plural': 'puntos de encuentro',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TransportePrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(choices=[('centro', 'Centro'), ('periferia', 'Periferia')], max_length=10, unique=True)),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio en pesos (MXN).', max_digits=10)),
                ('precio_base_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Precio en dolares. Vacio = no se ofrece en USD.', max_digits=10, null=True)),
                ('recargo_grupo', models.DecimalField(decimal_places=2, default=0, help_text='Se suma al precio base desde `min_personas_recargo` personas.', max_digits=10)),
                ('recargo_grupo_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_personas_recargo', models.PositiveSmallIntegerField(default=4)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'precio de transporte',
                'verbose_name_plural': 'precios de transporte',
                'ordering': ['zona'],
            },
        ),
    ]
