# Generated by Django 6.0.8 on 2026-08-28 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_extrasitem_puntoencuentro_transporteprecio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='precio_lunch',
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='precio_lunch_usd',
        ),
    ]
