# Generated by Django 6.0.8 on 2026-08-29 22:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_remove_tarifa_precio_lunch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, help_text='Uso interno, no se muestra al cliente.', max_length=200)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Vacio = vigente desde ya.', null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Vacio = sin fecha de expiracion.', null=True)),
                ('usos_maximos', models.PositiveIntegerField(blank=True, help_text='Vacio = sin limite.', null=True)),
                ('usos_maximos_por_cliente', models.PositiveSmallIntegerField(blank=True, help_text='Por correo del cliente. Vacio = sin limite.', null=True)),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, help_text='Minimo en pesos para que aplique. Vacio = sin minimo.', max_digits=10, null=True)),
                ('monto_minimo_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Minimo en dolares. Vacio = sin minimo en esa moneda.', max_digits=10, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'codigo promocional',
                'verbose_name_plural': 'codigos promocionales',
                'ordering': ['-creado_en'],
            },
        ),
    ]
