# Generated by Django 6.0.8 on 2026-08-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_codigopromocional'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrasitem',
            name='cantidad_editable',
            field=models.BooleanField(default=False, help_text='Si esta marcado, el checkout deja elegir cuantas personas del grupo lo necesitan (ej. licencia: alguien puede ya traer la suya tramitada aparte), en vez de aplicarlo a todo el grupo. Solo tiene sentido junto con "Cobrar por persona".'),
        ),
    ]
