# Generated by Django 6.0.8 on 2026-09-02 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_extrasitem_cantidad_editable'),
        ('tenancy', '0002_crear_sede_empresa_la_paz'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitan',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='capitanes', to='tenancy.empresa'),
        ),
        migrations.AddField(
            model_name='codigopromocional',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='codigos_promocionales', to='tenancy.empresa'),
        ),
        migrations.AddField(
            model_name='embarcacion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embarcaciones', to='tenancy.empresa'),
        ),
        migrations.AddField(
            model_name='embarcacionnodisponible',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embarcaciones_no_disponibles', to='tenancy.empresa'),
        ),
        migrations.AddField(
            model_name='extrasitem',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extras_items', to='tenancy.empresa'),
        ),
        migrations.AddField(
            model_name='puntoencuentro',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puntos_encuentro', to='tenancy.empresa'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarifa', to='tenancy.empresa'),
        ),
        migrations.AddField(
            model_name='transporteprecio',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='precios_transporte', to='tenancy.empresa'),
        ),
    ]
