# Generated by Django 6.0.8 on 2026-09-02 23:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_empresa_no_null'),
        ('tenancy', '0002_crear_sede_empresa_la_paz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigopromocional',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transporteprecio',
            name='zona',
            field=models.CharField(choices=[('centro', 'Centro'), ('periferia', 'Periferia')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='codigopromocional',
            constraint=models.UniqueConstraint(fields=('codigo', 'empresa'), name='codigopromocional_codigo_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='embarcacion',
            constraint=models.UniqueConstraint(fields=('nombre', 'empresa'), name='embarcacion_nombre_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='tarifa',
            constraint=models.UniqueConstraint(fields=('empresa',), name='tarifa_unica_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='transporteprecio',
            constraint=models.UniqueConstraint(fields=('zona', 'empresa'), name='transporteprecio_zona_unica_por_empresa'),
        ),
    ]
