# Generated by Django 6.0.8 on 2026-09-05 01:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_unicidad_por_empresa'),
        ('tenancy', '0003_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(default='otro', max_length=50)),
                ('cobrar_por_persona', models.BooleanField(default=False)),
                ('cantidad_editable', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personalizaciones', to='tenancy.empresa')),
            ],
            options={
                'verbose_name': 'personalización',
                'verbose_name_plural': 'personalizaciones',
                'ordering': ['empresa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('tipo_servicio', models.CharField(default='pesca', max_length=50)),
                ('estrategia_cupo', models.CharField(default='por_recurso_dia', max_length=50)),
                ('estrategia_precio', models.CharField(default='por_grupo', max_length=50)),
                ('modo_ocupacion', models.CharField(default='exclusivo', max_length=20)),
                ('precio_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio base del servicio en MXN.', max_digits=10)),
                ('precio_base_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Precio base del servicio en USD. Opcional.', max_digits=10, null=True)),
                ('precio_persona_extra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cargo por persona adicional arriba del cupo incluido en MXN.', max_digits=10)),
                ('precio_persona_extra_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Cargo por persona adicional arriba del cupo incluido en USD.', max_digits=10, null=True)),
                ('personas_incluidas', models.PositiveSmallIntegerField(default=3, help_text='Cantidad de personas incluidas en el precio base antes de cobrar recargo.')),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='tenancy.empresa')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['empresa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_maxima', models.PositiveSmallIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='tenancy.empresa')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='fleet.servicio')),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
                'ordering': ['empresa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioPersonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('precio_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('obligatorio', models.BooleanField(default=False)),
                ('preseleccionado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('personalizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_servicios', to='fleet.personalizacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicio_personalizaciones', to='fleet.servicio')),
            ],
            options={
                'verbose_name': 'personalización de servicio',
                'verbose_name_plural': 'personalizaciones de servicios',
                'ordering': ['servicio', 'personalizacion__nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='personalizacion',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='personalizacion_unica_por_empresa_nombre'),
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.UniqueConstraint(fields=('empresa', 'slug'), name='servicio_unico_por_empresa_slug'),
        ),
        migrations.AddConstraint(
            model_name='recurso',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='recurso_unico_por_empresa_nombre'),
        ),
        migrations.AddConstraint(
            model_name='serviciopersonalizacion',
            constraint=models.UniqueConstraint(fields=('servicio', 'personalizacion'), name='personalizacion_unica_por_servicio'),
        ),
    ]
