# Generated by Django 6.0.8 on 2026-09-06 00:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0018_crear_servicio_la_paz'),
        ('tenancy', '0003_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('precio_ancla', models.DecimalField(decimal_places=2, help_text='Precio ancla del paquete en pesos (MXN).', max_digits=10)),
                ('precio_ancla_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Precio ancla del paquete en dólares (USD). Opcional.', max_digits=10, null=True)),
                ('regla_precio', models.CharField(default='precio_ancla', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa_lider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes_liderados', to='tenancy.empresa')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='tenancy.sede')),
            ],
            options={
                'verbose_name': 'paquete',
                'verbose_name_plural': 'paquetes',
                'ordering': ['sede', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('removible', models.BooleanField(default=True)),
                ('ajuste_precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento sobre el precio ancla en MXN si el servicio es removido.', max_digits=10)),
                ('ajuste_precio_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento sobre el precio ancla en USD si el servicio es removido.', max_digits=10, null=True)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_asociados', to='fleet.paquete')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes_incluidos', to='fleet.servicio')),
            ],
            options={
                'verbose_name': 'servicio de paquete',
                'verbose_name_plural': 'servicios de paquetes',
                'ordering': ['paquete', 'orden', 'servicio__nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='paquete',
            constraint=models.UniqueConstraint(fields=('sede', 'slug'), name='paquete_unico_por_sede_slug'),
        ),
        migrations.AddConstraint(
            model_name='paqueteservicio',
            constraint=models.UniqueConstraint(fields=('paquete', 'servicio'), name='paqueteservicio_unico'),
        ),
    ]
