# Generated by Django 6.0.8 on 2026-09-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0020_rls_paquetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='porcentaje_anticipo',
            field=models.PositiveSmallIntegerField(default=30, help_text='% del total que se cobra en línea. 30=anticipo, 100=completo.'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estrategia_cupo',
            field=models.CharField(choices=[('por_recurso_dia', 'Por recurso por día'), ('por_noche', 'Por noche'), ('bajo_demanda', 'Bajo demanda')], default='por_recurso_dia', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estrategia_precio',
            field=models.CharField(choices=[('por_grupo', 'Por grupo'), ('por_persona', 'Por persona'), ('tarifa_fija', 'Tarifa fija'), ('por_noche', 'Por noche')], default='por_grupo', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='modo_ocupacion',
            field=models.CharField(choices=[('exclusivo', 'Exclusivo'), ('compartido', 'Compartido')], default='exclusivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('pesca', 'Pesca deportiva'), ('paseo', 'Paseo / Tour'), ('hospedaje', 'Hospedaje'), ('bajo_demanda', 'Bajo demanda')], default='pesca', max_length=20),
        ),
    ]
