# Generated by Django 6.0.8 on 2026-09-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0021_servicio_enums_y_anticipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='porcentaje_anticipo',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
