# Generated by Django 6.0.8 on 2026-09-07 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0022_paquete_porcentaje_anticipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paqueteservicio',
            name='ajuste_precio',
        ),
        migrations.RemoveField(
            model_name='paqueteservicio',
            name='ajuste_precio_usd',
        ),
        migrations.RemoveField(
            model_name='paqueteservicio',
            name='removible',
        ),
    ]
