# Generated by Django 6.0.8 on 2026-09-08 01:50

from django.db import migrations


def drop_rls_policy(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            DROP POLICY IF EXISTS tenancy_alcance ON fleet_transporteprecio;
            ALTER TABLE fleet_transporteprecio NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE fleet_transporteprecio DISABLE ROW LEVEL SECURITY;
        """)


def reapply_rls_policy(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE fleet_transporteprecio ENABLE ROW LEVEL SECURITY;
            ALTER TABLE fleet_transporteprecio FORCE ROW LEVEL SECURITY;
            CREATE POLICY tenancy_alcance ON fleet_transporteprecio
            FOR ALL
            USING (
              empresa_id = NULLIF(current_setting('app.current_empresa_id', true), '')::int
              OR current_setting('app.operador_plataforma', true) = 'on'
            );
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0023_remove_paqueteservicio_ajuste_precio_and_more'),
    ]

    operations = [
        migrations.RunPython(drop_rls_policy, reapply_rls_policy),
        migrations.RemoveConstraint(
            model_name='transporteprecio',
            name='transporteprecio_zona_unica_por_empresa',
        ),
        migrations.DeleteModel(
            name='TransportePrecio',
        ),
    ]
