# Generated by Django 6.0.8 on 2026-09-08 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0024_delete_transporteprecio'),
        ('tenancy', '0003_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporteTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_traslado', models.CharField(choices=[('redondo_aeropuerto', 'Redondo con aeropuerto'), ('redondo_actividad', 'Redondo actividad'), ('recepcion_aeropuerto', 'Recepción aeropuerto')], max_length=25)),
                ('zona', models.CharField(blank=True, choices=[('centro', 'Centro'), ('periferia', 'Periferia')], default='', max_length=10)),
                ('personas_min', models.PositiveSmallIntegerField(default=1)),
                ('personas_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas_transporte', to='tenancy.empresa')),
            ],
            options={
                'verbose_name': 'tarifa de transporte',
                'verbose_name_plural': 'tarifas de transporte',
                'ordering': ['empresa', 'tipo_traslado', 'zona', 'personas_min'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'tipo_traslado', 'zona', 'personas_min'), name='transportetarifa_unica'), models.CheckConstraint(condition=models.Q(models.Q(('tipo_traslado', 'redondo_actividad'), models.Q(('zona', ''), _negated=True)), models.Q(models.Q(('tipo_traslado', 'redondo_actividad'), _negated=True), ('zona', '')), _connector='OR'), name='transportetarifa_zona_solo_actividad')],
            },
        ),
    ]
