# Generated by Django 6.0.8 on 2026-09-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0026_rls_transportetarifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estrategia_precio',
            field=models.CharField(choices=[('por_grupo', 'Por grupo'), ('por_persona', 'Por persona'), ('tarifa_fija', 'Tarifa fija'), ('por_noche', 'Por noche'), ('por_ruta', 'Por ruta (transporte)')], default='por_grupo', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('pesca', 'Pesca deportiva'), ('paseo', 'Paseo / Tour'), ('hospedaje', 'Hospedaje'), ('bajo_demanda', 'Bajo demanda'), ('transporte', 'Transporte / Traslado')], default='pesca', max_length=20),
        ),
    ]
