# Generated by Django 6.0.8 on 2026-09-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0027_alter_servicio_estrategia_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='capacidad_maxima',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tope de personas por reserva de este servicio. Vacío = usa MAX_PERSONAS (5).', null=True),
        ),
    ]
