# Generated by Django 6.0.8 on 2026-09-12 08:51

from django.db import migrations, models


def normalizar_checks(apps, schema_editor):
    from apps.tenancy.rls import alcance_operador_migracion
    SP = apps.get_model('fleet', 'ServicioPersonalizacion')
    with alcance_operador_migracion(schema_editor.connection):
        SP.objects.using(schema_editor.connection.alias).filter(obligatorio=True).update(
            obligatorio=False, preseleccionado=True)


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0029_servicio_hora_apertura_servicio_hora_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacion',
            name='aviso_reforzado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalizacion',
            name='opciones_seleccion',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='personalizacion',
            name='tipo_interaccion',
            field=models.CharField(choices=[('check', 'Casilla'), ('input_texto', 'Texto'), ('input_numero', 'Número'), ('input_seleccion', 'Selección')], default='check', max_length=20),
        ),
        migrations.RunPython(normalizar_checks, migrations.RunPython.noop),
    ]
