# Generated by Django 6.0.8 on 2026-09-23 20:22

import django.core.validators
from django.db import migrations, models

from apps.tenancy.rls import alcance_operador_migracion


def marcar_permite_anticipo(apps, schema_editor):
    """Antes "sin anticipo" se codificaba con porcentaje 100. Ahora es un interruptor."""
    with alcance_operador_migracion(schema_editor.connection):
        for nombre in ('Servicio', 'Paquete'):
            modelo = apps.get_model('fleet', nombre)
            # Solo las filas que eran "sin anticipo" (100). Las demás ya quedan en True por el
            # default del AddField; NO se vuelve a activar nada después (reactivaría estas mismas
            # filas, que acaban de quedar con porcentaje 30).
            modelo.objects.filter(porcentaje_anticipo__gte=100).update(
                permite_anticipo=False, porcentaje_anticipo=30,
            )


def revertir_permite_anticipo(apps, schema_editor):
    with alcance_operador_migracion(schema_editor.connection):
        for nombre in ('Servicio', 'Paquete'):
            modelo = apps.get_model('fleet', nombre)
            modelo.objects.filter(permite_anticipo=False).update(porcentaje_anticipo=100)


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0034_retirar_extrasitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='permite_anticipo',
            field=models.BooleanField(default=True, help_text='Si está activo, el cliente puede elegir pagar solo el anticipo. Un paquete con servicios de dos empresas nunca admite anticipo.'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='permite_anticipo',
            field=models.BooleanField(default=True, help_text='Si está activo, el cliente puede elegir pagar solo el anticipo.'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='porcentaje_anticipo',
            field=models.PositiveSmallIntegerField(default=30, help_text='% del total que se cobra en línea si el cliente elige anticipo (1 a 99). Sustituye al anticipo de los servicios individuales del paquete.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='porcentaje_anticipo',
            field=models.PositiveSmallIntegerField(default=30, help_text='% del total que se cobra en línea si el cliente elige anticipo (1 a 99). Solo aplica si "permite anticipo" está activo.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.RunPython(marcar_permite_anticipo, revertir_permite_anticipo),
    ]
