# Generated by Django 6.0.8 on 2026-09-23 22:08

from django.db import migrations, models

from apps.tenancy.rls import alcance_operador_migracion


def noches_por_omision(apps, schema_editor):
    with alcance_operador_migracion(schema_editor.connection):
        modelo = apps.get_model('fleet', 'PaqueteServicio')
        modelo.objects.filter(
            servicio__estrategia_cupo='por_noche', noches__isnull=True,
        ).update(noches=1)


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0035_anticipo_explicito'),
    ]

    operations = [
        migrations.AddField(
            model_name='paqueteservicio',
            name='dia_estancia',
            field=models.PositiveSmallIntegerField(default=1, help_text='Día del paquete en que ocurre este servicio (1 = día de llegada).'),
        ),
        migrations.AddField(
            model_name='paqueteservicio',
            name='noches',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Solo hospedaje: noches que incluye el paquete. El cliente no las elige.', null=True),
        ),
        migrations.AddField(
            model_name='paqueteservicio',
            name='personas_incluidas',
            field=models.PositiveSmallIntegerField(default=2, help_text='Lugares de este servicio que incluye el paquete. El cliente puede usar menos sin que cambie el precio.'),
        ),
        migrations.RunPython(noches_por_omision, migrations.RunPython.noop),
    ]
