# Generated by Django 6.0.8 on 2026-09-24 17:16

import django.db.models.deletion
from django.db import migrations, models

from apps.tenancy.rls import alcance_operador_migracion


def rellenar_empresa(apps, schema_editor):
    """Filas anteriores a este campo: la empresa es la de su servicio."""
    with alcance_operador_migracion(schema_editor.connection):
        modelo = apps.get_model('fleet', 'PaqueteServicio')
        for ps in modelo.objects.select_related('servicio').filter(empresa__isnull=True):
            modelo.objects.filter(pk=ps.pk).update(empresa_id=ps.servicio.empresa_id)


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0036_paqueteservicio_estancia_personas'),
        ('tenancy', '0003_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='paqueteservicio',
            name='empresa',
            field=models.ForeignKey(blank=True, editable=False, help_text='Copia de la empresa del servicio. Permite contar las empresas de un paquete sin unir con Servicio, que RLS oculta entre empresas.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.empresa'),
        ),
        migrations.RunPython(rellenar_empresa, migrations.RunPython.noop),
    ]
