# Generated by Django 6.0.8 on 2026-10-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0037_paqueteservicio_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='precio_por_persona',
            field=models.BooleanField(default=False, help_text='Si está activo, el precio ancla (MXN y USD) es el de UNA persona y el total es precio × personas. Apagado, el precio ancla es un total fijo del paquete.'),
        ),
    ]
