# Generated by Django 6.0.8 on 2026-10-01 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0038_paquete_precio_por_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='paqueteservicio',
            name='salidas',
            field=models.PositiveSmallIntegerField(default=1, help_text='Solo actividades: cuántos días SEGUIDOS se repite, empezando en el día indicado arriba. Ejemplo: día 2 con 4 salidas = días 2, 3, 4 y 5. Debe caber dentro de la estancia.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
