# Generated by Django 6.0.8 on 2026-10-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0039_paqueteservicio_salidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='solo_en_paquete',
            field=models.BooleanField(default=False, help_text='Si está activo, el servicio solo se vende dentro de un paquete: no aparece en el catálogo suelto ni se puede reservar o pagar por separado.'),
        ),
    ]
