# Generated by Django 6.0.8 on 2026-10-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0040_servicio_solo_en_paquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='pide_hora',
            field=models.BooleanField(default=True, help_text='Si está activo, el cliente elige la hora de salida al reservar. Apágalo en un paquete con hospedaje donde la hora la acuerda el capitán durante la estadía: la reserva queda sin hora.'),
        ),
    ]
