# Generated by Django 6.0.8 on 2026-10-02 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0041_pide_hora_y_hora_opcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='paso_hora_minutos',
            field=models.PositiveSmallIntegerField(default=15, help_text='Cada cuántos minutos se ofrece una hora dentro del rango (5 a 240).', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AddField(
            model_name='servicio',
            name='pide_hora',
            field=models.BooleanField(default=True, help_text='Si está activo, el cliente elige la hora de salida dentro del rango (apertura a cierre). Apágalo en servicios sin hora de salida, como el hospedaje.'),
        ),
    ]
