# Generated by Django 6.0.8 on 2026-10-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0043_horas_de_servicios_existentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codigopromocional',
            name='monto_minimo_usd',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='precio_ancla_usd',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='precio_base_usd',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='precio_persona_extra_usd',
        ),
        migrations.RemoveField(
            model_name='serviciopersonalizacion',
            name='precio_usd',
        ),
        migrations.RemoveField(
            model_name='transportetarifa',
            name='precio_usd',
        ),
        migrations.AlterField(
            model_name='codigopromocional',
            name='monto_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimo en pesos para que aplique. Vacio = sin minimo. En dolares se calcula con el tipo de cambio de la sede.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='precio_por_persona',
            field=models.BooleanField(default=False, help_text='Si está activo, el precio ancla es el de UNA persona y el total es precio × personas. Apagado, el precio ancla es un total fijo del paquete.'),
        ),
    ]
